name: ESPHome config 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
    - uses: actions/checkout@v4
    - name: Define cofnig files
      id: config
      run: |
        CONFIG=$(scripts/find-config.sh)
        echo ${CONFIG}
        echo "config=${CONFIG}" >> "$GITHUB_OUTPUT"

  check-config:
    runs-on: ubuntu-latest
    needs:
      - define-matrix
    strategy:
      matrix:
        config_file: ${{ fromJSON(needs.define-matrix.outputs.config) }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "requirements**.txt"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt
  
    - name: Prepare secrets
      run: |
        cp config/secrets-example.yaml sensors/secrets.yaml
        cp config/secrets-example.yaml displays/secrets.yaml
        cp config/secrets-example.yaml camera/secrets.yaml

    - name: Check Config ${{matrix.config_file}}
      run: |
        esphome config ${{matrix.config_file}}
  
    - name: Check Compile ${{matrix.config_file}}
      run: |
        esphome compile ${{matrix.config_file}}
