name: ESPHome config 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - name: Define cofnig files
        id: config
        run: |
          echo 'config=$(scripts/find-config.sh)' >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs:
      - define-matrix
    strategy:
      matrix:
        config_file: ${{ fromJSON(needs.define-matrix.outputs.config) }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: "pip"
        cache-dependency-path: "**/requirements.txt"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure secrets
      run: |
        cp config/secrets-example.yaml sensors/secrets.yaml
        cp config/secrets-example.yaml displays/secrets.yaml
        cp config/secrets-example.yaml camera/secrets.yaml

    - name: Verify ${config_file
      run: |
        echo Verifying ${config_file}
        esphome config ${config_file}
        esphome compile ${config_file}
